"use client";

import type { Dispatch, RefObject, SetStateAction } from "react";
import type { AIModelOption, ExternalSource, LabelTemplate, LabelTemplateMeta, PrinterStatus, SidebarFavorite, User } from "@/lib/api";
import type { DateFormat, PrintMode } from "@/lib/app-context-storage";
import type { AIProfileDraft, AISettingsDraft, ExternalSourceDraft, LabelTemplateDraft } from "@/components/settings/drafts";
import type { Locale } from "@/lib/i18n-data";
import type { LocationHealthResult } from "./settings-page-actions";

export type SettingsPageSectionsProps = {
  activeSection: string;
  me: User | null;
  t: (key: string, vars?: Record<string, string | number>) => string;
  can: (permission: string) => boolean;
  isAdmin: boolean;
  locale: Locale;
  setLocale: (value: Locale) => void;
  dateFormat: DateFormat;
  setDateFormat: (value: DateFormat) => void;
  itemsPerPage: number;
  setItemsPerPage: (value: number) => void;
  iosDeleteConfirm: boolean;
  setIosDeleteConfirm: (value: boolean) => void;
  showItemImages: boolean;
  setShowItemImages: (value: boolean) => void;
  showItemPlaceholders: boolean;
  setShowItemPlaceholders: (value: boolean) => void;
  showItemCategory: boolean;
  setShowItemCategory: (value: boolean) => void;
  showItemLocation: boolean;
  setShowItemLocation: (value: boolean) => void;
  showItemDescription: boolean;
  setShowItemDescription: (value: boolean) => void;
  showItemStock: boolean;
  setShowItemStock: (value: boolean) => void;
  showItemConsumable: boolean;
  setShowItemConsumable: (value: boolean) => void;
  showItemPrice: boolean;
  setShowItemPrice: (value: boolean) => void;
  showItemTotal: boolean;
  setShowItemTotal: (value: boolean) => void;
  showItemProperties: boolean;
  setShowItemProperties: (value: boolean) => void;
  showItemActivity: boolean;
  setShowItemActivity: (value: boolean) => void;
  showAttachmentUploadOnItemDetail: boolean;
  setShowAttachmentUploadOnItemDetail: (value: boolean) => void;
  itemStockWarningPercent: number;
  setItemStockWarningPercent: (value: number) => void;
  itemStockCriticalPercent: number;
  setItemStockCriticalPercent: (value: number) => void;
  maintenanceLeadDays: number;
  setMaintenanceLeadDays: (value: number) => void;
  maintenanceSettingsSaving: boolean;
  saveMaintenanceSettings: () => Promise<void>;
  sidebarFavorites: SidebarFavorite[];
  setSidebarFavorites: Dispatch<SetStateAction<SidebarFavorite[]>>;
  sidebarFavoritesSaving: boolean;
  saveSidebarFavorites: () => Promise<void>;
  localeOptions: { value: Locale; label: string }[];
  titleDraft: string;
  titleSizeDraft: number;
  titlePositionDraft: "right" | "below";
  subtitleDraft: string;
  footerTextDraft: string;
  widthDraft: number;
  logoBackgroundDraft: string;
  logoPaddingDraft: number;
  logoRadiusDraft: number;
  brandingStatus: string | null;
  logoInputRef: RefObject<HTMLInputElement | null>;
  setTitleDraft: Dispatch<SetStateAction<string>>;
  setTitleSizeDraft: Dispatch<SetStateAction<number>>;
  setTitlePositionDraft: Dispatch<SetStateAction<"right" | "below">>;
  setSubtitleDraft: Dispatch<SetStateAction<string>>;
  setFooterTextDraft: Dispatch<SetStateAction<string>>;
  setWidthDraft: Dispatch<SetStateAction<number>>;
  setLogoBackgroundDraft: Dispatch<SetStateAction<string>>;
  setLogoPaddingDraft: Dispatch<SetStateAction<number>>;
  setLogoRadiusDraft: Dispatch<SetStateAction<number>>;
  setLogoDraft: Dispatch<SetStateAction<string | null>>;
  setBrandingStatus: Dispatch<SetStateAction<string | null>>;
  onLogoSelect: (file?: File | null) => void;
  saveBranding: () => Promise<void>;
  resetBranding: () => void;
  printMode: PrintMode;
  setPrintMode: (value: PrintMode) => void;
  showPrintFeatures: boolean;
  setShowPrintFeatures: (value: boolean) => void;
  printer: PrinterStatus | null;
  setPrinter: Dispatch<SetStateAction<PrinterStatus | null>>;
  templateMeta: LabelTemplateMeta | null;
  templates: LabelTemplate[];
  selectedTemplateId: number | "new" | null;
  setSelectedTemplateId: Dispatch<SetStateAction<number | "new" | null>>;
  templateDraft: LabelTemplateDraft;
  setTemplateDraft: Dispatch<SetStateAction<LabelTemplateDraft>>;
  canManageTemplates: boolean;
  createNewTemplate: () => void;
  savePrinterConfig: () => void;
  calibratePrinter: () => void;
  saveTemplate: () => void;
  deleteTemplate: () => void;
  makeDefaultTemplate: () => void;
  printTemplateNow: () => void;
  loadDefaultTSPL: () => void;
  externalSources: ExternalSource[];
  selectedExternalSourceId: number | "new" | null;
  setSelectedExternalSourceId: Dispatch<SetStateAction<number | "new" | null>>;
  externalSourceDraft: ExternalSourceDraft;
  setExternalSourceDraft: Dispatch<SetStateAction<ExternalSourceDraft>>;
  selectedExternalSource: ExternalSource | null;
  externalSourceBusy: "hostkey" | "test" | null;
  createNewExternalSource: () => void;
  fetchExternalSourceHostKey: () => void;
  testExternalSource: () => void;
  saveExternalSource: () => void;
  deleteExternalSource: () => void;
  aiDraft: AISettingsDraft;
  setAiDraft: Dispatch<SetStateAction<AISettingsDraft>>;
  selectedAIProfileId: string;
  setSelectedAIProfileId: Dispatch<SetStateAction<string>>;
  aiTesting: boolean;
  aiModelsLoading: boolean;
  saveAISettings: () => Promise<void>;
  testAISettings: () => Promise<void>;
  loadAIModels: (profile: AIProfileDraft) => Promise<AIModelOption[]>;
  backupBusy: "export" | "recover" | null;
  recoverFile: File | null;
  recoverInputRef: RefObject<HTMLInputElement | null>;
  recoverSelection: { database: boolean; attachments: boolean; config: boolean };
  setRecoverFile: Dispatch<SetStateAction<File | null>>;
  setRecoverSelection: Dispatch<SetStateAction<{ database: boolean; attachments: boolean; config: boolean }>>;
  exportBackupBundle: () => Promise<void>;
  recoverBackupBundle: () => Promise<void>;
  checkLocations: () => Promise<void>;
  locIssues: LocationHealthResult | null;
  locFixing: boolean;
  fixLocations: () => Promise<void>;
  accountInfoRows: { label: string; value: string }[];
  accountPermissions: string[];
  accountActiveCheckouts: number;
  accountDeleteDisabled: boolean;
  deleteAccountBusy: boolean;
  displayNameDraft: string;
  setDisplayNameDraft: Dispatch<SetStateAction<string>>;
  avatarInputRef: RefObject<HTMLInputElement | null>;
  saveAccount: () => Promise<void>;
  uploadAccountAvatar: (file?: File | null) => Promise<void>;
  removeAccountAvatar: () => Promise<void>;
  deleteAccount: () => Promise<void>;
  settingsPrimaryButtonClass: string;
  settingsSecondaryButtonClass: string;
  settingsDangerButtonClass: string;
  settingsInputClass: string;
  settingsMonoTextareaClass: string;
};
